"""Theme constants for the JARVIS desktop UI."""

import customtkinter as ctk

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("dark-blue")

BG = "#070B1A"
PANEL = "#101A36"
PANEL_SOFT = "#162248"
RING_BRIGHT = "#37E7FF"
RING_MID = "#2A9FD6"
RING_DIM = "#1D4F75"
RING_GLOW = "#00C2FF"
ARC_CYAN = "#4AF7FF"
ARC_AMBER = "#F2A33A"
ARC_GOLD = "#F6D365"
TEXT_WHITE = "#EEF5FF"
TEXT_SUB = "#9CB4C8"
TEXT_GREEN = "#65D28A"
TEXT_AMBER = "#F2B84B"
STATUS_RED = "#EF6B73"
TICK_MAJOR = "#5AB9E6"
TICK_MINOR = "#204D72"
SCAN_LINE = "#2D79AD"
INNER_FILL = "#0D1735"
BORDER = "#2A5E8A"

BTN_PRIMARY = "#1E5C9A"
BTN_PRIMARY_HOVER = "#2772BC"
BTN_SECONDARY = "#1C6B62"
BTN_SECONDARY_HOVER = "#26877B"
BTN_WARN = "#8A5A16"
BTN_WARN_HOVER = "#A46F1D"
BTN_DANGER = "#7C2532"
BTN_DANGER_HOVER = "#963243"
BTN_DANGER_BORDER = "#E06A75"
INPUT_BG = "#0C1633"
LOG_BG = "#0A1630"
ORB_SCALE = 0.60

ICON_LOGO = "[*]"
ICON_STATUS = "*"
ICON_SECTION = "::"
ICON_INPUT = ">"

TEXT_ONLINE = f"{ICON_STATUS} ONLINE"
TEXT_PROCESSING = f"{ICON_STATUS} PROCESSING"
TEXT_LISTENING = f"{ICON_STATUS} LISTENING"
TEXT_SPEAKING = f"{ICON_STATUS} SPEAKING"
TEXT_AUTHENTICATING = f"{ICON_STATUS} AUTHENTICATING"
TEXT_LOCKED = f"{ICON_STATUS} LOCKED"

LABEL_VOICE = "VOICE COMMAND"
LABEL_LISTENING = "LISTENING..."
LABEL_GREETING = "GREETING"
LABEL_STOP_SPEAKING = "STOP SPEAKING"
LABEL_REAUTH = "RE-AUTHENTICATE"
LABEL_CLEAR_LOG = "CLEAR LOG"
